export interface IResonseTali {
  fecha: string;
  data: Datum[];
}

export interface Datum {
  shift: number;
  line: number;
  prod_date: string;
  vessel_lot: string;
  vessel_name: string;
  final_species: string;
  final_species_size: string;
  species_code: number;
  final_control_no: string;
  final_control_sprayed: number;
  mp_calculada: number;
  mp_calculada_perc: number;
  final_trolley_count: number;
  net_weight_crudo: number;
  loin_kg: number;
  flake_kg: number;
  other_loin_kg: number;
  other_flake_kg: number;
  total_loin: number;
  total_flake: number;
  relac: number;
  weight_kg_rociado: number;
  weight_kg_cocido: number;
  cleaning_type: string;
  piezas: number;
  factor: number;
  exponente: number;
  peso_prom: number;
  loin_pct: number;
  flake_pct: number;
  rend_curva: number;
  curva_pct: null | number;
  merma_perc: number;
  total_reject: number;
  bleach_weight: number;
  distributed_value: number;
  std_loin: number;
  rend_kg_field: number;
  yield_expected_lomo: number;
  yield_expected_flake: number;
  lomo_esperado_kg: number;
  flake_esperado_kg: number;
}



export const dataAR:IResonseTali[] = [
    {
      fecha: "2022-10-06",
      data: [
        {
          shift: 2,
          line: 5,
          prod_date: "2022-10-06",
          vessel_lot: "16-7-2022",
          vessel_name: "DON ANTONIO",
          final_species: "YF",
          final_species_size: "YELLOW FIN 7.5-9",
          species_code: 1.009,
          final_control_no: "053",
          final_control_sprayed: 45,
          mp_calculada: 3136,
          mp_calculada_perc: 0.28,
          final_trolley_count: 7,
          net_weight_crudo: 2949,
          loin_kg: 1043.68,
          flake_kg: 0,
          other_loin_kg: 62.26,
          other_flake_kg: 0,
          total_loin: 1105.94,
          total_flake: 33.32,
          relac: 97.08,
          weight_kg_rociado: 2584,
          weight_kg_cocido: 2601,
          cleaning_type: "Double Clean",
          piezas: 862,
          factor: 43,
          exponente: 0.0699,
          peso_prom: 8.02,
          loin_pct: 35.27,
          flake_pct: 1.06,
          rend_curva: 49.74,
          curva_pct: 73.04,
          merma_perc: 12.38,
          total_reject: 0,
          bleach_weight: 119,
          distributed_value: 33.32,
          std_loin: 82,
          rend_kg_field: 1559.85,
          yield_expected_lomo: 83,
          yield_expected_flake: 16,
          lomo_esperado_kg: 1294.67,
          flake_esperado_kg: 251.8
        },
        {
          shift: 2,
          line: 5,
          prod_date: "2022-10-06",
          vessel_lot: "16-7-2022",
          vessel_name: "DON ANTONIO",
          final_species: "YF",
          final_species_size: "YELLOW FIN 11.5-12.5",
          species_code: 1.012,
          final_control_no: "057",
          final_control_sprayed: 45,
          mp_calculada: 1544,
          mp_calculada_perc: 0.14,
          final_trolley_count: 4,
          net_weight_crudo: 1447,
          loin_kg: 681.37,
          flake_kg: 0,

          other_loin_kg: 0,
          other_flake_kg: 0,
          total_loin: 681.37,
          total_flake: 16.66,
          relac: 97.61,
          weight_kg_rociado: 1262,
          weight_kg_cocido: 1276,
          cleaning_type: "Double Clean",
          piezas: 357,
          factor: 43,
          exponente: 0.0699,
          peso_prom: 9.53,
          loin_pct: 44.13,
          flake_pct: 1.08,

          rend_curva: 50.34,
          curva_pct: 89.81,
          merma_perc: 12.79,
          total_reject: 0,
          bleach_weight: 119,
          distributed_value: 16.66,
          std_loin: 82,
          rend_kg_field: 777.25,
          yield_expected_lomo: 83,
          yield_expected_flake: 16,
          lomo_esperado_kg: 645.12,
          flake_esperado_kg: 124.36
        },
        {
          shift: 2,
          line: 5,
          prod_date: "2022-10-06",
          vessel_lot: "784-7-2022",
          vessel_name: "CAP. DANNY B",
          final_species: "YF",
          final_species_size: "YELLOW FIN 4-5",
          species_code: 1.006,
          final_control_no: "059",
          final_control_sprayed: 49,
          mp_calculada: 2536.8243911719937,
          mp_calculada_perc: 0.22,
          final_trolley_count: 6,
          net_weight_crudo: 2357,
          loin_kg: 833.58,
          flake_kg: 197.77,
          other_loin_kg: 30.98,
          other_flake_kg: 7.42,
          total_loin: 864.56,
          total_flake: 231.37,
          relac: 78.89,
          weight_kg_rociado: 2018,
          weight_kg_cocido: 2032,
          cleaning_type: "Double Clean",
          piezas: 1196,
          factor: 43,
          exponente: 0.0699,
          peso_prom: 4.68,
          loin_pct: 34.08,
          flake_pct: 9.12,
          rend_curva: 47.9,
          curva_pct: 90.19,
          merma_perc: 14.38,
          total_reject: 0,
          bleach_weight: 119,
          distributed_value: 26.18,
          std_loin: 82,
          rend_kg_field: 1215.14,
          yield_expected_lomo: 83,
          yield_expected_flake: 16,
          lomo_esperado_kg: 1008.57,
          flake_esperado_kg: 194.42
        },
        {
          shift: 2,
          line: 5,
          prod_date: "2022-10-06",
          vessel_lot: "111-05-2022",
          vessel_name: "ALESSIA",
          final_species: "SJ",
          final_species_size: "SKIP JACK -2",
          species_code: 2.002,
          final_control_no: "065",
          final_control_sprayed: 54,
          mp_calculada: 1395.2586872586874,
          mp_calculada_perc: 0.19,
          final_trolley_count: 4,
          net_weight_crudo: 1337,
          loin_kg: 509.23,
          flake_kg: 403.83,
          other_loin_kg: 67.15,
          other_flake_kg: 19.37,
          total_loin: 576.38,
          total_flake: 423.2,
          relac: 57.66,
          weight_kg_rociado: 1140.5,
          weight_kg_cocido: 1151.5,
          cleaning_type: "Regular Clean",
          piezas: 1945,
          factor: 41,
          exponente: 0.095,
          peso_prom: 1.58,
          loin_pct: 41.31,
          flake_pct: 30.33,
          rend_curva: 42.82,
          curva_pct: 167.3,
          merma_perc: 14.7,
          total_reject: 0,
          bleach_weight: 0,
          distributed_value: 0,
          std_loin: 88,
          rend_kg_field: 597.45,
          yield_expected_lomo: 88,
          yield_expected_flake: 12,
          lomo_esperado_kg: 525.76,
          flake_esperado_kg: 71.69
      },
      {
          shift: 2,
          line: 6,
          prod_date: "2022-10-06",
          vessel_lot: "784-7-2022",
          vessel_name: "CAP. DANNY B",
          final_species: "YF",
          final_species_size: "YELLOW FIN 6-7.5",
          species_code: 1.008,
          final_control_no: "069",
          final_control_sprayed: 49,
          mp_calculada: 4106.413284132841,
          mp_calculada_perc: 0.36,
          final_trolley_count: 11,
          net_weight_crudo: 3844,
          loin_kg: 1350.88,
          flake_kg: 156.38,
          other_loin_kg: 53.24,
          other_flake_kg: 41.51,
          total_loin: 1404.12,
          total_flake: 240.73,
          relac: 85.36,
          weight_kg_rociado: 3195.5,
          weight_kg_cocido: 3260.5,
          cleaning_type: "Double Clean",
          piezas: 1698,
          factor: 43,
          exponente: 0.0699,
          peso_prom: 5.33,
          loin_pct: 34.19,
          flake_pct: 5.86,
          rend_curva: 48.34,
          curva_pct: 82.87,
          merma_perc: 16.87,
          total_reject: 0,
          bleach_weight: 119,
          distributed_value: 42.84,
          std_loin: 82,
          rend_kg_field: 1985.04,
          yield_expected_lomo: 83,
          yield_expected_flake: 16,
          lomo_esperado_kg: 1647.58,
          flake_esperado_kg: 317.61
      },
      {
          shift: 2,
          line: 6,
          prod_date: "2022-10-06",
          vessel_lot: "365-4-2022",
          vessel_name: "JOCAY",
          final_species: "SJ",
          final_species_size: "SKIP JACK 11.5-12.5 LBS",
          species_code: 2.012,
          final_control_no: "043",
          final_control_sprayed: 38,
          mp_calculada: 6397,
          mp_calculada_perc: 0.41,
          final_trolley_count: 14,
          net_weight_crudo: 6114,
          loin_kg: 0,
          flake_kg: 64.51,
          other_loin_kg: 58.3,
          other_flake_kg: 8.66,
          total_loin: 58.3,
          total_flake: 73.17,
          relac: 44.34,
          weight_kg_rociado: 5135.5,
          weight_kg_cocido: 5173.5,
          cleaning_type: "Single Clean",
          piezas: 1478,
          factor: 41,
          exponente: 0.095,
          peso_prom: 9.54,
          loin_pct: 0.91,
          flake_pct: 1.14,
          rend_curva: 50.8,
          curva_pct: 4.06,
          merma_perc: 16,
          total_reject: 0,
          bleach_weight: 0,
          distributed_value: 0,
          std_loin: 88,
          rend_kg_field: 3249.68,
          yield_expected_lomo: 93,
          yield_expected_flake: 7,
          lomo_esperado_kg: 3022.2,
          flake_esperado_kg: 227.48
      },
      {
          shift: 2,
          line: 6,
          prod_date: "2022-10-06",
          vessel_lot: "382-3-2022",
          vessel_name: "MIRANDA",
          final_species: "SJ",
          final_species_size: "SKIP JACK 7.5-9 LB",
          species_code: 2.009,
          final_control_no: "047",
          final_control_sprayed: 40,
          mp_calculada: 3195.2398444252376,
          mp_calculada_perc: 0.2,
          final_trolley_count: 7,
          net_weight_crudo: 3015,
          loin_kg: 1380.04,
          flake_kg: 170.51,
          other_loin_kg: 27.25,
          other_flake_kg: 7.98,
          total_loin: 1407.29,
          total_flake: 178.49,
          relac: 88.74,
          weight_kg_rociado: 2478,
          weight_kg_cocido: 2579,
          cleaning_type: "Regular Clean",
          piezas: 810,
          factor: 41,
          exponente: 0.095,
          peso_prom: 8.7,
          loin_pct: 44.04,
          flake_pct: 5.59,
          rend_curva: 50.35,
          curva_pct: 98.57,
          merma_perc: 17.81,
          total_reject: 0,
          bleach_weight: 0,
          distributed_value: 0,
          std_loin: 88,
          rend_kg_field: 1608.8,
          yield_expected_lomo: 88,
          yield_expected_flake: 12,
          lomo_esperado_kg: 1415.75,
          flake_esperado_kg: 193.06
      },
      {
          shift: 2,
          line: 6,
          prod_date: "2022-10-06",
          vessel_lot: "104-3-2022",
          vessel_name: "UGAVI",
          final_species: "SJ",
          final_species_size: "SKIP JACK 2-3 LBS",
          species_code: 2.003,
          final_control_no: "052",
          final_control_sprayed: 44,
          mp_calculada: 4409.444397223403,
          mp_calculada_perc: 0.28,
          final_trolley_count: 9,
          net_weight_crudo: 4439,
          loin_kg: 0,
          flake_kg: 147.8,
          other_loin_kg: 131.75,
          other_flake_kg: 22.35,
          total_loin: 131.75,
          total_flake: 170.15,
          relac: 43.64,
          weight_kg_rociado: 3696,
          weight_kg_cocido: 3732,
          cleaning_type: "Regular Clean",
          piezas: 3349,
          factor: 41,
          exponente: 0.095,
          peso_prom: 2.9,
          loin_pct: 2.99,
          flake_pct: 3.86,
          rend_curva: 45.37,
          curva_pct: 15.1,
          merma_perc: 16.74,
          total_reject: 0,
          bleach_weight: 0,
          distributed_value: 0,
          std_loin: 88,
          rend_kg_field: 2000.56,
          yield_expected_lomo: 88,
          yield_expected_flake: 12,
          lomo_esperado_kg: 1760.5,
          flake_esperado_kg: 240.07
      },
      {
          shift: 2,
          line: 6,
          prod_date: "2022-10-06",
          vessel_lot: "306-4-2022",
          vessel_name: "GIULIETTA",
          final_species: "YF",
          final_species_size: "YELLOW FIN 12.5-14",
          species_code: 1.014,
          final_control_no: "070",
          final_control_sprayed: 55,
          mp_calculada: 104,
          mp_calculada_perc: 0.05,
          final_trolley_count: 1,
          net_weight_crudo: 95,
          loin_kg: 0,
          flake_kg: 0,
          other_loin_kg: 38.81,
          other_flake_kg: 15.12,
          total_loin: 38.81,
          total_flake: 15.12,
          relac: 71.96,
          weight_kg_rociado: 83,
          weight_kg_cocido: 84,
          cleaning_type: "Double Clean",
          piezas: 18,
          factor: 43,
          exponente: 0.0699,
          peso_prom: 12.74,
          loin_pct: 37.32,
          flake_pct: 14.54,
          rend_curva: 51.37,
          curva_pct: 100.95,
          merma_perc: 12.63,
          total_reject: 0,
          bleach_weight: 0,
          distributed_value: 0,
          std_loin: 82,
          rend_kg_field: 53.42,
          yield_expected_lomo: 83,
          yield_expected_flake: 16,
          lomo_esperado_kg: 44.34,
          flake_esperado_kg: 8.55
      }]

    
    }
    ,
    {
      fecha: "2022-10-06",
      data: [
        {
          shift: 2,
          line: 6,
          prod_date: "2022-10-06",
          vessel_lot: "306-4-2022",
          vessel_name: "GIULIETTA",
          final_species: "YF",
          final_species_size: "YELLOW FIN 11.5-12.5",
          species_code: 1.012,
          final_control_no: "071",
          final_control_sprayed: 55,
          mp_calculada: 107,
          mp_calculada_perc: 0.05,
          final_trolley_count: 1,
          net_weight_crudo: 88,
          loin_kg: 0,
          flake_kg: 0,
          other_loin_kg: 0,
          other_flake_kg: 0,
          total_loin: 0,
          total_flake: 0,
          relac: 0,
          weight_kg_rociado: 75.5,
          weight_kg_cocido: 76,
          cleaning_type: "Double Clean",
          piezas: 25,
          factor: 43,
          exponente: 0.0699,
          peso_prom: 9.44,
          loin_pct: 0,
          flake_pct: 0,
          rend_curva: 50.3,
          curva_pct: 0,
          merma_perc: 14.2,
          total_reject: 0,
          bleach_weight: 0,
          distributed_value: 0,
          std_loin: 82,
          rend_kg_field: 53.82,
          yield_expected_lomo: 83,
          yield_expected_flake: 16,
          lomo_esperado_kg: 44.67,
          flake_esperado_kg: 8.61
      },
      {
          shift: 2,
          line: 6,
          prod_date: "2022-10-06",
          vessel_lot: "306-4-2022",
          vessel_name: "GIULIETTA",
          final_species: "YF",
          final_species_size: "YELLOW FIN 2-3",
          species_code: 1.003,
          final_control_no: "072",
          final_control_sprayed: 55,
          mp_calculada: 898,
          mp_calculada_perc: 0.4,
          final_trolley_count: 2,
          net_weight_crudo: 900,
          loin_kg: 0,
          flake_kg: 50.87,
          other_loin_kg: 20.97,
          other_flake_kg: 0,
          total_loin: 20.97,
          total_flake: 50.87,
          relac: 29.19,
          weight_kg_rociado: 762.5,
          weight_kg_cocido: 772,
          cleaning_type: "Double Clean",
          piezas: 748,
          factor: 43,
          exponente: 0.0699,
          peso_prom: 2.65,
          loin_pct: 2.34,
          flake_pct: 5.66,
          rend_curva: 46.03,
          curva_pct: 17.38,
          merma_perc: 15.28,
          total_reject: 0,
          bleach_weight: 0,
          distributed_value: 0,
          std_loin: 82,
          rend_kg_field: 413.35,
          yield_expected_lomo: 83,
          yield_expected_flake: 16,
          lomo_esperado_kg: 343.08,
          flake_esperado_kg: 66.14
      },
      {
          shift: 2,
          line: 6,
          prod_date: "2022-10-06",
          vessel_lot: "03-4-2022",
          vessel_name: "ROCIO",
          final_species: "YF",
          final_species_size: "YELLOW FIN 20-40",
          species_code: 1.019,
          final_control_no: "077",
          final_control_sprayed: 58,
          mp_calculada: 1005,
          mp_calculada_perc: 0.45,
          final_trolley_count: 3,
          net_weight_crudo: 906,
          loin_kg: 0,
          flake_kg: 0,
          other_loin_kg: 0,
          other_flake_kg: 0,
          total_loin: 0,
          total_flake: 0,
          relac: 0,
          weight_kg_rociado: 794,
          weight_kg_cocido: 802,
          cleaning_type: "Double Clean",
          piezas: 71,
          factor: 43,
          exponente: 0.0699,
          peso_prom: 31.21,
          loin_pct: 0,
          flake_pct: 0,
          rend_curva: 54.69,
          curva_pct: 0,
          merma_perc: 12.36,
          total_reject: 0,
          bleach_weight: 0,
          distributed_value: 0,
          std_loin: 82,
          rend_kg_field: 549.63,
          yield_expected_lomo: 83,
          yield_expected_flake: 16,
          lomo_esperado_kg: 456.2,
          flake_esperado_kg: 87.94
      },
      {
          shift: 2,
          line: 6,
          prod_date: "2022-10-06",
          vessel_lot: "306-4-2022",
          vessel_name: "GIULIETTA",
          final_species: "YF",
          final_species_size: "YELLOW FIN 16-18",
          species_code: 1.017,
          final_control_no: "078",
          final_control_sprayed: 55,
          mp_calculada: 115,
          mp_calculada_perc: 0.05,
          final_trolley_count: 1,
          net_weight_crudo: 101,
          loin_kg: 0,
          flake_kg: 0,
          other_loin_kg: 0,
          other_flake_kg: 0,
          total_loin: 0,
          total_flake: 0,
          relac: 0,
          weight_kg_rociado: 88.5,
          weight_kg_cocido: 89,
          cleaning_type: "Double Clean",
          piezas: 14,
          factor: 43,
          exponente: 0.0699,
          peso_prom: 18.11,
          loin_pct: 0,
          flake_pct: 0,
          rend_curva: 52.65,
          curva_pct: 0,
          merma_perc: 12.38,
          total_reject: 0,
          bleach_weight: 0,
          distributed_value: 0,
          std_loin: 82,
          rend_kg_field: 60.55,
          yield_expected_lomo: 83,
          yield_expected_flake: 16,
          lomo_esperado_kg: 50.25,
          flake_esperado_kg: 9.69
      }]
    }
]

